# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7cf8d90be19da053cadab401e7af87774ed4db0e48cd5df4d650b3961936dea505620539ac2d539f25c80e53a36ae86ebbea05fc1dd7e7ef2f6b3f3e6d52ade

test:
  secret_key_base: 63e169c7ef034014c7a4c7caf2ce1fa6ede8ef5c58f16b18c72f514e3ca497fbb7eb888a1b106257b32875723154b080bdd18e97118b21836dad0ac356ad5b66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
